# See https://pre-commit.com/ for usage and config
fail_fast: true
repos:
  # https://github.com/pre-commit/pre-commit-hooks/releases/tag/v4.3.0
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [ --fix, auto ]
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: name-tests-test
        args: [ --pytest-test-first ]
      - id: check-case-conflict
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [ commit ]
        language: system
        entry: pipenv run isort
        types: [ python ]
      - id: black
        name: black
        stages: [ commit ]
        language: system
        entry: pipenv run black
        types: [ python ]
      - id: flake8
        name: flake8
        stages: [ commit ]
        language: system
        entry: pipenv run flake8
        types: [ python ]
        exclude: setup.py
      - id: mypy
        name: mypy
        stages: [ commit ]
        language: system
        entry: pipenv run mypy
        types: [ python ]
        require_serial: true
      - id: pytest
        name: pytest
        stages: [ commit ]
        language: system
        # https://github.com/pytest-dev/pytest/issues/5502#issuecomment-1020761655
        # Prevent Pytest logging error like: ValueError: I/O operation on closed file.
        entry: env LOG_LEVEL=DEBUG pipenv run pytest --cov --cov-report html --html=./build/.pytest_report/report.html --self-contained-html --log-cli-level=DEBUG -n auto --benchmark-disable
        types: [ python ]
        pass_filenames: false
      - id: pytest-cov
        name: pytest
        stages: [ push ]
        language: system
        # https://github.com/pytest-dev/pytest/issues/5502#issuecomment-1020761655
        # Prevent Pytest logging error like: ValueError: I/O operation on closed file.
        entry: env LOG_LEVEL=ERROR pipenv run pytest --cov --cov-fail-under=90 --capture=no --log-cli-level=ERROR -n auto
        types: [ python ]
        pass_filenames: false
